### ISSUE TITLE
Error Initialising...

### ISSUE THREAD

**Issue by Alcedema** [Webreaper/QbtManager#3]
On Linux Mint 19.2..

Since 1.2, setting deleteFiles to either true or false and not setting email or rssfeeds, as not needed for me, I get the following error on execution:

[21:14:24.604--INF] Getting Seeding Task list and mapping trackers...
[21:14:24.953--INF] Processing torrent list...
[21:14:24.968--INF] Error initialising. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at QbtManager.MainClass.<>c__DisplayClass4_0.<ProcessTorrents>b__0(Tracker x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at QbtManager.MainClass.ProcessTorrents(qbtService service, IList`1 tasks, Settings settings)
   at QbtManager.MainClass.Main(String[] args)

**Comment by Webreaper** [comment]
Fixed in v1.3
